name: warehouse_management
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  cached_network_image: ^3.1.0
  cloud_firestore: ^2.5.3
  double_back_to_close_app: ^2.0.1
  firebase_auth: ^3.1.3
  firebase_core: ^1.7.0
  flutter:
    sdk: flutter
  flutter_svg: ^0.22.0
  fluttertoast: ^8.0.8
  intl: ^0.17.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.7.2

flutter:
  uses-material-design: true
  fonts:
    - family: Nunito
      fonts:
      - asset: lib/assets/fonts/Nunito/Nunito-Bold.ttf
      - asset: lib/assets/fonts/Nunito/Nunito-Light.ttf
      - asset: lib/assets/fonts/Nunito/Nunito-Regular.ttf

    - family: Open_Sans
      fonts:
      - asset: lib/assets/fonts/Open_Sans/OpenSans-Bold.ttf
      - asset: lib/assets/fonts/Open_Sans/OpenSans-Light.ttf
      - asset: lib/assets/fonts/Open_Sans/OpenSans-Regular.ttf